name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5.0.0
      
      - uses: dtolnay/rust-toolchain@stable
        id: toolchain
      
      - name: Cache Rust, Cargo and project deps
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            book/
          key: ${{ runner.os }}-cargo-${{ steps.toolchain.outputs.cachekey }}
          
      - name: Install MdBook and Dependencies
        run: which mdbook || cargo install mdbook --no-default-features --features search --vers "^0.4" --locked
          
      - name: install linkcheck
        run: which mdbook-linkcheck || cargo install mdbook-linkcheck --vers "^0.7.7" --locked
      
      - name: install admonish
        run: which mdbook-admonish || cargo install mdbook-admonish --vers "^1.20.0" --locked

      - name: Build the Book
        run: mdbook build
        
      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./book/html

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
